### ISSUE TITLE
Additional filters on REST endpoint

### ISSUE THREAD

**Issue by petenelson** [10up/wp-content-connect#29]
We have a use case where we:

- We're editing a child post
- We need to add a relationship limited to only other child posts for the current post's parent post

The proposal would be:

- Send the current post ID/user ID and the relationship name in the REST request to provider better context to the REST endpoint
- Add filters to the `search_users()` and `search_posts()` functions that pass the query args as well as the ID and relationship name to allow the query args to be adjusted as-needed

I can work on a PR for this if it seems reasonable.

**Comment by jeffpaul** [comment]
Resolved by #35
