### ISSUE TITLE
Test against WP 5.3

### ISSUE THREAD

**Issue by jeffpaul** [10up/wp-content-connect#46]
**Is your enhancement related to a problem? Please describe.**
Now that [WordPress 5.3 is released](https://wordpress.org/news/2019/11/kirk/), we'll want to test WP Content Connect to see if any incompatibility issues arise.

**Describe the solution you'd like**
- [ ] test WP Content Connect on WP 5.3
- [ ] open issues for any incompatibilities noted in testing
- [ ] resolve issues identified in testing
- [ ] bump "tested up to" version
- [ ] if code changes needed due to incompatibilities, ship a plugin release

**Designs**
n/a

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by dinhtungdu** [comment]
I tested this plugin against WP 5.3.2 and I don't have any issue. Tests performed.
- Create a relationship between post types, the meta boxes function normally for both Classis Editor and Gutenberg.
- Create a relationship between post and user, the meta boxes function normally for both Classis Editor and Gutenberg.
- Can query posts with`relationship_query` for both  `related_to_user` and `related_to_post`, the queries returned correct posts.

Currently, we don't store tested up to value anywhere in our plugin. I don't think we should make changes to the main plugin file just for updating the tested up to version. We also don't have a `readme.txt` file, so updating `README.md` makes more sense. @jeffpaul Do we have any plan to release this plugin to `.org`?

**Comment by jeffpaul** [comment]
@dinhtungdu let's add the WP tested badge to this repo, similar to what's in-use on ClassifAI: https://github.com/10up/classifai
