### ISSUE TITLE
"Notice: Function post_type was called incorrectly" on new WooCommerce orders edit screen

### ISSUE THREAD

**Issue by webdados** [10up/wp-content-connect#76]
### Describe the bug

If WooCommerce is active and using the new High Performance order Tables, this plugin throws several notices on the order edit screen (wp-admin/admin.php?page=wc-orders&action=edit&id=12345)

`Notice: Function post_type was called incorrectly. Order properties should not be accessed directly. Backtrace: do_action('load-woocommerce_page_wc-orders'), WP_Hook->do_action, WP_Hook->apply_filters, Automattic\WooCommerce\Internal\Admin\Orders\PageController->__call, call_user_func_array, Automattic\WooCommerce\Internal\Admin\Orders\PageController->handle_load_page_action, Automattic\WooCommerce\Internal\Admin\Orders\PageController->setup_action_edit_order, Automattic\WooCommerce\Internal\Admin\Orders\PageController->prepare_order_edit_form, Automattic\WooCommerce\Internal\Admin\Orders\Edit->setup, do_action('add_meta_boxes'), WP_Hook->do_action, WP_Hook->apply_filters, TenUp\ContentConnect\UI\MetaBox->add_meta_boxes, apply_filters('tenup_content_connect_post_relationship_data'), WP_Hook->apply_filters, TenUp\ContentConnect\UI\PostToPost->filter_data, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Please see Debugging in WordPress for more information. (This message was added in version 3.0.) in /Users/marcoalmeida/Documents/Websites/_local/wordpress-testing/app/public/wp-includes/functions.php on line 6078`

### Steps to Reproduce

1. Activate this plugin
2. Activate WooCommerce
3. Activate HPOS on WooCommerce
4. Got to a order edit screen and see the notices

### Screenshots, screen recording, code snippet

<img width="1079" alt="image" src="https://github.com/10up/wp-content-connect/assets/6853605/800ccb02-074e-4c59-b4eb-3bd740c2cb64">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by s3rgiosan** [comment]
@jeffpaul @rickalee this PR #77 addresses this issue.
